# Site settings

title: Colton Dick | Professional Portfolio
url: "https://coltondick.github.io"
baseurl: ""

# OPTIONAL CHANGES
bio-page-label: Resume
theme-home: theme-home-builtin-1.html
theme-bio: theme-bio-builtin-1.html

# Specify the rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: igorpro

# No need to change the following
markdown: kramdown
include: [_data]
