# Site settings

title: Colton Dick | Professional Portfolio
url: "https://coltondick.github.io"
baseurl: ""

# OPTIONAL CHANGES
theme-home: home.html

# Specify the rouge syntax highlighter theme. Pick one from css/rouge.
rouge-theme: igorpro

# Style will be applied only after restarting the build or serve. Just choose one of the options.
theme_skin: nordic # blue turquoise green berry orange ceramic
chrome_mobile_color: #use hex colors (ex:#1976d2) or leave empty if you don't want a color for chrome mobile searchbar

# Tracker
analytics: G-FW0L3TZKT2

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Build settings
compress-site: yes

encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

# Development Settings
port: 4001
host: 0.0.0.0
safe: false

# No need to change the following
markdown: kramdown
include: [_data]
